# --------------------------- PAIS

# --- !Ups

CREATE SEQUENCE PAIS_ID_SEQ;
CREATE TABLE PAIS
(
	ID INTEGER NOT NULL DEFAULT NEXTVAL('PAIS_ID_SEQ'),
	DESCRICAO VARCHAR(30) NOT NULL,
	DESCRICAONACIONALIDADE VARCHAR(30) NULL
);

# --- !Downs

DROP TABLE PAIS;
DROP SEQUENCE PAIS_ID_SEQ;

# --------------------------- UF

# --- !Ups

CREATE SEQUENCE UF_ID_SEQ;
CREATE TABLE UF
(
	ID INTEGER NOT NULL DEFAULT NEXTVAL('UF_ID_SEQ'),
	PAIS_ID INTEGER NOT NULL,
	SIGLA VARCHAR(10) NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	FOREIGN KEY (PAIS_ID) REFERENCES PAIS(ID)
);

# --- !Downs

DROP TABLE UF;
DROP SEQUENCE UF_ID_SEQ;

# --- !Ups

INSERT INTO PAIS(DESCRICAO, DESCRICAONACIONALIDADE) VALUES ('BRASIL', 'BRASILEIRO');

INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'AC', 'AC');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'AL', 'AL');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'AP', 'AP');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'AM', 'AM');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'BA', 'BA');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'CE', 'CE');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'DF', 'DF');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'ES', 'ES');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'GO', 'GO');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'MA', 'MA');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'MT', 'MT');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'MS', 'MS');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'MG', 'MG');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'PA', 'PA');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'PB', 'PB');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'PR', 'PR');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'PE', 'PE');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'PI', 'PI');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'RJ', 'RJ');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'RN', 'RN');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'RS', 'RS');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'RO', 'RO');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'RR', 'RR');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'SC', 'SC');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'SP', 'SP');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'SE', 'SE');
INSERT INTO UF(PAIS_ID, SIGLA, NOME) VALUES ((SELECT ID FROM PAIS WHERE DESCRICAO = 'BRASIL'), 'TO', 'TO');